import { BookCategory, CuratedBook } from '@/types';

export interface CuratedBookCategory {
  name: BookCategory;
  color: string;
  bgClass: string;
}

export const BOOK_CATEGORIES: CuratedBookCategory[] = [
  { name: 'Habits', color: 'text-emerald-400', bgClass: 'bg-emerald-500/15 border-emerald-500/30' },
  { name: 'Mindset', color: 'text-purple-400', bgClass: 'bg-purple-500/15 border-purple-500/30' },
  { name: 'Productivity', color: 'text-blue-400', bgClass: 'bg-blue-500/15 border-blue-500/30' },
  { name: 'Discipline', color: 'text-orange-400', bgClass: 'bg-orange-500/15 border-orange-500/30' },
  { name: 'Finance', color: 'text-amber-400', bgClass: 'bg-amber-500/15 border-amber-500/30' },
  { name: 'Relationships', color: 'text-rose-400', bgClass: 'bg-rose-500/15 border-rose-500/30' },
  { name: 'Spirituality', color: 'text-teal-400', bgClass: 'bg-teal-500/15 border-teal-500/30' },
  { name: 'Business', color: 'text-cyan-400', bgClass: 'bg-cyan-500/15 border-cyan-500/30' },
  { name: 'Influence', color: 'text-indigo-400', bgClass: 'bg-indigo-500/15 border-indigo-500/30' },
];

export function getCategoryMeta(category: BookCategory): CuratedBookCategory {
  return BOOK_CATEGORIES.find((c) => c.name === category) ?? BOOK_CATEGORIES[0];
}

export const CURATED_BOOKS: CuratedBook[] = [
  {
    id: 'curated-atomic-habits',
    title: 'Atomic Habits',
    author: 'James Clear',
    description:
      'An easy & proven way to build good habits & break bad ones. Tiny changes, remarkable results. Focus on 1% improvements every day.',
    category: 'Habits',
    isCurated: true,
    pointsOnCompletion: 40,
    pointsReward: 40,
    totalPages: 320,
    totalAmount: 320,
    trendingRank: 1,
    bestSellerRank: 3,
  },
  {
    id: 'curated-7-habits',
    title: 'The 7 Habits of Highly Effective People',
    author: 'Stephen R. Covey',
    description:
      'A principle-centered framework for personal and interpersonal effectiveness. Move from dependence to independence to interdependence.',
    category: 'Habits',
    isCurated: true,
    pointsOnCompletion: 45,
    pointsReward: 45,
    totalPages: 381,
    totalAmount: 381,
    trendingRank: 9,
    bestSellerRank: 5,
  },
  {
    id: 'curated-deep-work',
    title: 'Deep Work',
    author: 'Cal Newport',
    description:
      'Rules for focused success in a distracted world. Cultivate the ability to focus without distraction on cognitively demanding tasks.',
    category: 'Productivity',
    isCurated: true,
    pointsOnCompletion: 35,
    pointsReward: 35,
    totalPages: 304,
    totalAmount: 304,
    trendingRank: 10,
    bestSellerRank: 18,
  },
  {
    id: 'curated-power-of-now',
    title: 'The Power of Now',
    author: 'Eckhart Tolle',
    description:
      'A guide to spiritual enlightenment. Learn to transcend ego-based thinking and embrace the present moment to find peace and fulfillment.',
    category: 'Spirituality',
    isCurated: true,
    pointsOnCompletion: 30,
    pointsReward: 30,
    totalPages: 236,
    totalAmount: 236,
    trendingRank: 16,
    bestSellerRank: 10,
  },
  {
    id: 'curated-cant-hurt-me',
    title: "Can't Hurt Me",
    author: 'David Goggins',
    description:
      'Master your mind and defy the odds. A story of extreme perseverance showing how to callous your mind, overcome pain, and reach your full potential.',
    category: 'Discipline',
    isCurated: true,
    pointsOnCompletion: 50,
    pointsReward: 50,
    totalPages: 364,
    totalAmount: 364,
    trendingRank: 5,
    bestSellerRank: 12,
  },
  {
    id: 'curated-think-grow-rich',
    title: 'Think and Grow Rich',
    author: 'Napoleon Hill',
    description:
      'The classic guide to wealth-building philosophy. Thirteen proven steps toward riches and the power of organized, personal initiative.',
    category: 'Finance',
    isCurated: true,
    pointsOnCompletion: 35,
    pointsReward: 35,
    totalPages: 238,
    totalAmount: 238,
    trendingRank: 8,
    bestSellerRank: 2,
  },
  {
    id: 'curated-subtle-art',
    title: "The Subtle Art of Not Giving a F*ck",
    author: 'Mark Manson',
    description:
      'A counterintuitive approach to living a good life. Let go of what you think your life should be and embrace the messiness of reality.',
    category: 'Mindset',
    isCurated: true,
    pointsOnCompletion: 30,
    pointsReward: 30,
    totalPages: 224,
    totalAmount: 224,
    trendingRank: 12,
    bestSellerRank: 7,
  },
  {
    id: 'curated-mindset',
    title: 'Mindset: The New Psychology of Success',
    author: 'Carol S. Dweck',
    description:
      'How we can learn to fulfill our potential by adopting a growth mindset over a fixed mindset. The power of believing you can improve.',
    category: 'Mindset',
    isCurated: true,
    pointsOnCompletion: 35,
    pointsReward: 35,
    totalPages: 320,
    totalAmount: 320,
    trendingRank: 19,
    bestSellerRank: 19,
  },
  {
    id: 'curated-alchemist',
    title: 'The Alchemist',
    author: 'Paulo Coelho',
    description:
      'A mystical fable about following your dreams. A shepherd boy embarks on a journey to find his personal legend and discovers treasures within.',
    category: 'Spirituality',
    isCurated: true,
    pointsOnCompletion: 25,
    pointsReward: 25,
    totalPages: 208,
    totalAmount: 208,
    trendingRank: 6,
    bestSellerRank: 1,
  },
  {
    id: 'curated-ikigai',
    title: 'Ikigai: The Japanese Secret to a Long and Happy Life',
    author: 'Hector Garcia & Francesc Miralles',
    description:
      'Find your reason for being. The intersection of what you love, what you are good at, what the world needs, and what you can be paid for.',
    category: 'Mindset',
    isCurated: true,
    pointsOnCompletion: 25,
    pointsReward: 25,
    totalPages: 208,
    totalAmount: 208,
    trendingRank: 38,
    bestSellerRank: 36,
  },
  {
    id: 'curated-compound-effect',
    title: 'The Compound Effect',
    author: 'Darren Hardy',
    description:
      'Multiplying your success, one simple step at a time. Small, smart, consistent choices + time = radical difference between where you are and where you want to be.',
    category: 'Productivity',
    isCurated: true,
    pointsOnCompletion: 30,
    pointsReward: 30,
    totalPages: 192,
    totalAmount: 192,
    trendingRank: 23,
    bestSellerRank: 24,
  },
  {
    id: 'curated-mans-search',
    title: "Man's Search for Meaning",
    author: 'Viktor E. Frankl',
    description:
      'Lessons from a Nazi concentration camp on the importance of finding purpose and meaning in suffering, and how that drives the will to survive.',
    category: 'Spirituality',
    isCurated: true,
    pointsOnCompletion: 40,
    pointsReward: 40,
    totalPages: 165,
    totalAmount: 165,
    trendingRank: 14,
    bestSellerRank: 8,
  },
  {
    id: 'curated-rich-dad-poor-dad',
    title: 'Rich Dad Poor Dad',
    author: 'Robert Kiyosaki',
    description:
      'Challenges traditional beliefs about money and investing. Learn how acquiring assets and building financial literacy creates true independence.',
    category: 'Finance',
    isCurated: true,
    pointsOnCompletion: 40,
    pointsReward: 40,
    totalPages: 336,
    totalAmount: 336,
    trendingRank: 4,
    bestSellerRank: 6,
  },
  {
    id: 'curated-intelligent-investor',
    title: 'The Intelligent Investor',
    author: 'Benjamin Graham',
    description:
      'The definitive handbook on value investing and risk management. Master emotional discipline and long-term portfolio growth.',
    category: 'Finance',
    isCurated: true,
    pointsOnCompletion: 50,
    pointsReward: 50,
    totalPages: 640,
    totalAmount: 640,
    trendingRank: 17,
    bestSellerRank: 14,
  },
  {
    id: 'curated-millionaire-next-door',
    title: 'The Millionaire Next Door',
    author: 'Thomas J. Stanley',
    description:
      'Surprising secrets of America’s wealthy through frugality and discipline. Learn how living below your means leads to real wealth accumulation.',
    category: 'Finance',
    isCurated: true,
    pointsOnCompletion: 35,
    pointsReward: 35,
    totalPages: 258,
    totalAmount: 258,
    trendingRank: 25,
    bestSellerRank: 22,
  },
  {
    id: 'curated-secrets-millionaire-mind',
    title: 'Secrets of the Millionaire Mind',
    author: 'T. Harv Eker',
    description:
      'Reset your internal money and success blueprint. Recondition subconscious beliefs to attract and sustain enduring abundance.',
    category: 'Finance',
    isCurated: true,
    pointsOnCompletion: 35,
    pointsReward: 35,
    totalPages: 224,
    totalAmount: 224,
    trendingRank: 34,
    bestSellerRank: 34,
  },
  {
    id: 'curated-science-getting-rich',
    title: 'The Science of Getting Rich',
    author: 'Wallace D. Wattles',
    description:
      'A timeless formula for creating wealth through purposeful thought and decisive action. Harmonize clear ambition with creative gratitude.',
    category: 'Finance',
    isCurated: true,
    pointsOnCompletion: 30,
    pointsReward: 30,
    totalPages: 112,
    totalAmount: 112,
    trendingRank: 39,
    bestSellerRank: 38,
  },
  {
    id: 'curated-cashflow-quadrant',
    title: "Rich Dad's Cashflow Quadrant",
    author: 'Robert Kiyosaki',
    description:
      'A guide to financial freedom across Employee, Self-Employed, Business, and Investor paths. Master the shift toward passive income generation.',
    category: 'Finance',
    isCurated: true,
    pointsOnCompletion: 40,
    pointsReward: 40,
    totalPages: 384,
    totalAmount: 384,
    trendingRank: 29,
    bestSellerRank: 32,
  },
  {
    id: 'curated-psychology-of-money',
    title: 'The Psychology of Money',
    author: 'Morgan Housel',
    description:
      'Timeless lessons on wealth, greed, and happiness. Understand that doing well with money is far more about behavior than raw intelligence.',
    category: 'Finance',
    isCurated: true,
    pointsOnCompletion: 40,
    pointsReward: 40,
    totalPages: 256,
    totalAmount: 256,
    trendingRank: 2,
    bestSellerRank: 11,
  },
  {
    id: 'curated-millionaire-fastlane',
    title: 'The Millionaire Fastlane',
    author: 'MJ DeMarco',
    description:
      'Crack the code to accelerated wealth creation through entrepreneurship. Escape the slow financial treadmill and engineer scalable value.',
    category: 'Finance',
    isCurated: true,
    pointsOnCompletion: 45,
    pointsReward: 45,
    totalPages: 336,
    totalAmount: 336,
    trendingRank: 15,
    bestSellerRank: 21,
  },
  {
    id: 'curated-money-master-the-game',
    title: 'Money Master the Game',
    author: 'Tony Robbins',
    description:
      '7 simple steps to financial freedom from world-class financial minds. Build an all-weather investment blueprint for lifelong security.',
    category: 'Finance',
    isCurated: true,
    pointsOnCompletion: 50,
    pointsReward: 50,
    totalPages: 688,
    totalAmount: 688,
    trendingRank: 35,
    bestSellerRank: 35,
  },
  {
    id: 'curated-tax-free-wealth',
    title: 'Tax-Free Wealth',
    author: 'Tom Wheelwright',
    description:
      'How to use the tax code to legally build massive wealth. Transform government tax incentives into powerful engines of business growth.',
    category: 'Finance',
    isCurated: true,
    pointsOnCompletion: 35,
    pointsReward: 35,
    totalPages: 272,
    totalAmount: 272,
    trendingRank: 48,
    bestSellerRank: 48,
  },
  {
    id: 'curated-abcs-real-estate-investing',
    title: 'The ABCs of Real Estate Investing',
    author: 'Ken McElroy',
    description:
      'Fundamental strategies for finding, evaluating, and managing cash-flowing real estate. Unlock passive cash flow through disciplined property acquisition.',
    category: 'Finance',
    isCurated: true,
    pointsOnCompletion: 35,
    pointsReward: 35,
    totalPages: 224,
    totalAmount: 224,
    trendingRank: 49,
    bestSellerRank: 49,
  },
  {
    id: 'curated-creature-jekyll-island',
    title: 'The Creature from Jekyll Island',
    author: 'G. Edward Griffin',
    description:
      'A deep-dive investigation into the origins and mechanisms of the Federal Reserve. Understand central banking, fiat currency, and inflation.',
    category: 'Finance',
    isCurated: true,
    pointsOnCompletion: 50,
    pointsReward: 50,
    totalPages: 608,
    totalAmount: 608,
    trendingRank: 51,
    bestSellerRank: 51,
  },
  {
    id: 'curated-house-of-morgan',
    title: 'The House of Morgan',
    author: 'Ron Chernow',
    description:
      'An epic history of the American banking dynasty that shaped global finance. Witness the rise, power, and transformation of Wall Street.',
    category: 'Finance',
    isCurated: true,
    pointsOnCompletion: 50,
    pointsReward: 50,
    totalPages: 812,
    totalAmount: 812,
    trendingRank: 52,
    bestSellerRank: 52,
  },
  {
    id: 'curated-devil-take-the-hindmost',
    title: 'Devil Take the Hindmost',
    author: 'Edward Chancellor',
    description:
      'A captivating history of financial speculation and market bubbles. Learn crucial psychological lessons from three centuries of economic euphoria.',
    category: 'Finance',
    isCurated: true,
    pointsOnCompletion: 45,
    pointsReward: 45,
    totalPages: 384,
    totalAmount: 384,
    trendingRank: 53,
    bestSellerRank: 53,
  },
  {
    id: 'curated-power-of-habit',
    title: 'The Power of Habit',
    author: 'Charles Duhigg',
    description:
      'Explores the neurological loop of cue, routine, and reward. Learn how individual and organizational habits can be reshaped for lasting change.',
    category: 'Habits',
    isCurated: true,
    pointsOnCompletion: 45,
    pointsReward: 45,
    totalPages: 371,
    totalAmount: 371,
    trendingRank: 21,
    bestSellerRank: 20,
  },
  {
    id: 'curated-10x-rule',
    title: 'The 10X Rule',
    author: 'Grant Cardone',
    description:
      'The sole difference between success and failure is taking massive action. Multiply your effort by ten to shatter self-imposed limitations.',
    category: 'Mindset',
    isCurated: true,
    pointsOnCompletion: 35,
    pointsReward: 35,
    totalPages: 240,
    totalAmount: 240,
    trendingRank: 26,
    bestSellerRank: 25,
  },
  {
    id: 'curated-magic-thinking-big',
    title: 'The Magic of Thinking Big',
    author: 'David J. Schwartz',
    description:
      'Achieve exponential success by expanding your mental horizon. Overcome excuse-itis, conquer self-doubt, and cultivate high-level ambition.',
    category: 'Mindset',
    isCurated: true,
    pointsOnCompletion: 40,
    pointsReward: 40,
    totalPages: 320,
    totalAmount: 320,
    trendingRank: 28,
    bestSellerRank: 27,
  },
  {
    id: 'curated-how-to-raise-self-esteem',
    title: 'How to Raise Your Self-Esteem',
    author: 'Nathaniel Branden',
    description:
      'Actionable sentence-completion exercises to build authentic self-worth. Cultivate genuine self-acceptance, personal integrity, and emotional resilience.',
    category: 'Mindset',
    isCurated: true,
    pointsOnCompletion: 30,
    pointsReward: 30,
    totalPages: 176,
    totalAmount: 176,
    trendingRank: 43,
    bestSellerRank: 43,
  },
  {
    id: 'curated-ten-days-to-self-esteem',
    title: 'Ten Days to Self-Esteem',
    author: 'David D. Burns',
    description:
      'Evidence-based cognitive behavioral techniques to dismantle negative self-talk. Uncover distorted thoughts and replace them with empowering clarity.',
    category: 'Mindset',
    isCurated: true,
    pointsOnCompletion: 40,
    pointsReward: 40,
    totalPages: 336,
    totalAmount: 336,
    trendingRank: 44,
    bestSellerRank: 44,
  },
  {
    id: 'curated-subconscious-mind',
    title: 'The Power of Your Subconscious Mind',
    author: 'Joseph Murphy',
    description:
      'Unlock the hidden reserves of your mind to overcome obstacles and manifest prosperity. Channel mental affirmations to reshape daily reality.',
    category: 'Mindset',
    isCurated: true,
    pointsOnCompletion: 35,
    pointsReward: 35,
    totalPages: 304,
    totalAmount: 304,
    trendingRank: 31,
    bestSellerRank: 30,
  },
  {
    id: 'curated-stop-worrying-start-living',
    title: 'How to Stop Worrying and Start Living',
    author: 'Dale Carnegie',
    description:
      'Practical, time-tested formulas to conquer chronic anxiety and fatigue. Learn to live in day-tight compartments and banish destructive worry.',
    category: 'Mindset',
    isCurated: true,
    pointsOnCompletion: 40,
    pointsReward: 40,
    totalPages: 352,
    totalAmount: 352,
    trendingRank: 33,
    bestSellerRank: 31,
  },
  {
    id: 'curated-power-positive-thinking',
    title: 'The Power of Positive Thinking',
    author: 'Norman Vincent Peale',
    description:
      'Practical spiritual techniques to build faith in yourself and eliminate defeatist attitudes. Harness calm confidence to achieve life goals.',
    category: 'Mindset',
    isCurated: true,
    pointsOnCompletion: 35,
    pointsReward: 35,
    totalPages: 304,
    totalAmount: 304,
    trendingRank: 32,
    bestSellerRank: 29,
  },
  {
    id: 'curated-laws-of-human-nature',
    title: 'The Laws of Human Nature',
    author: 'Robert Greene',
    description:
      'Master self-awareness and decode people’s hidden motivations and psychological biases. Transform destructive emotional impulses into rational influence.',
    category: 'Mindset',
    isCurated: true,
    pointsOnCompletion: 50,
    pointsReward: 50,
    totalPages: 624,
    totalAmount: 624,
    trendingRank: 18,
    bestSellerRank: 26,
  },
  {
    id: 'curated-misbehaving',
    title: 'Misbehaving: The Making of Behavioral Economics',
    author: 'Richard H. Thaler',
    description:
      'How human irrationality challenges standard economic theory. Discover how cognitive quirks and real behavior drive real-world choices.',
    category: 'Mindset',
    isCurated: true,
    pointsOnCompletion: 45,
    pointsReward: 45,
    totalPages: 432,
    totalAmount: 432,
    trendingRank: 45,
    bestSellerRank: 45,
  },
  {
    id: 'curated-four-agreements',
    title: 'The Four Agreements',
    author: 'Don Miguel Ruiz',
    description:
      'A practical guide to personal freedom based on ancient Toltec wisdom. Transform life through impeccable word, non-attachment, and doing your best.',
    category: 'Spirituality',
    isCurated: true,
    pointsOnCompletion: 30,
    pointsReward: 30,
    totalPages: 160,
    totalAmount: 160,
    trendingRank: 13,
    bestSellerRank: 9,
  },
  {
    id: 'curated-the-secret',
    title: 'The Secret',
    author: 'Rhonda Byrne',
    description:
      'Harness the universal Law of Attraction to align thought, emotion, and action. Direct intentional focus to create abundance and well-being.',
    category: 'Mindset',
    isCurated: true,
    pointsOnCompletion: 30,
    pointsReward: 30,
    totalPages: 216,
    totalAmount: 216,
    trendingRank: 30,
    bestSellerRank: 28,
  },
  {
    id: 'curated-reality-transurfing',
    title: 'Reality Transurfing',
    author: 'Vadim Zeland',
    description:
      'A transformative model for navigating alternative reality tracks without struggle. Free yourself from energetic pendulums to choose your destiny.',
    category: 'Spirituality',
    isCurated: true,
    pointsOnCompletion: 50,
    pointsReward: 50,
    totalPages: 560,
    totalAmount: 560,
    trendingRank: 40,
    bestSellerRank: 42,
  },
  {
    id: 'curated-unscripted',
    title: 'Unscripted',
    author: 'MJ DeMarco',
    description:
      'Break free from the conventional corporate script and build an authentic life. Engineer an enterprise that creates true autonomy and generational wealth.',
    category: 'Business',
    isCurated: true,
    pointsOnCompletion: 45,
    pointsReward: 45,
    totalPages: 434,
    totalAmount: 434,
    trendingRank: 37,
    bestSellerRank: 39,
  },
  {
    id: 'curated-personal-mba',
    title: 'The Personal MBA',
    author: 'Josh Kaufman',
    description:
      'A world-class business education condensing core commercial principles. Master value creation, marketing, sales, value delivery, and finance.',
    category: 'Business',
    isCurated: true,
    pointsOnCompletion: 50,
    pointsReward: 50,
    totalPages: 496,
    totalAmount: 496,
    trendingRank: 27,
    bestSellerRank: 33,
  },
  {
    id: 'curated-4-hour-workweek',
    title: 'The 4-Hour Workweek',
    author: 'Tim Ferriss',
    description:
      'Escape the 9-to-5, live anywhere, and join the new rich. Leverage lifestyle design, selective outsourcing, and ruthless elimination of non-essentials.',
    category: 'Productivity',
    isCurated: true,
    pointsOnCompletion: 45,
    pointsReward: 45,
    totalPages: 416,
    totalAmount: 416,
    trendingRank: 22,
    bestSellerRank: 15,
  },
  {
    id: 'curated-lean-startup',
    title: 'The Lean Startup',
    author: 'Eric Ries',
    description:
      'How constant innovation creates radically successful businesses. Test ideas rapidly through minimum viable products and validated learning cycles.',
    category: 'Business',
    isCurated: true,
    pointsOnCompletion: 40,
    pointsReward: 40,
    totalPages: 336,
    totalAmount: 336,
    trendingRank: 20,
    bestSellerRank: 17,
  },
  {
    id: 'curated-dotcom-secrets',
    title: 'Dotcom Secrets',
    author: 'Russell Brunson',
    description:
      'The underground playbook for growing your company online with sales funnels. Master value ladders, attractive characters, and conversion psychology.',
    category: 'Business',
    isCurated: true,
    pointsOnCompletion: 40,
    pointsReward: 40,
    totalPages: 384,
    totalAmount: 384,
    trendingRank: 36,
    bestSellerRank: 37,
  },
  {
    id: 'curated-psychology-of-selling',
    title: 'The Psychology of Selling',
    author: 'Brian Tracy',
    description:
      'Increase your sales faster and easier than you ever thought possible. Master inner game confidence, prospect psychology, and persuasive closing.',
    category: 'Influence',
    isCurated: true,
    pointsOnCompletion: 35,
    pointsReward: 35,
    totalPages: 240,
    totalAmount: 240,
    trendingRank: 41,
    bestSellerRank: 40,
  },
  {
    id: 'curated-greatest-salesman',
    title: 'The Greatest Salesman in the World',
    author: 'Og Mandino',
    description:
      'A timeless allegory providing ten transformative scrolls on life philosophy. Build unshakable perseverance, master emotions, and serve with love.',
    category: 'Influence',
    isCurated: true,
    pointsOnCompletion: 30,
    pointsReward: 30,
    totalPages: 128,
    totalAmount: 128,
    trendingRank: 42,
    bestSellerRank: 41,
  },
  {
    id: 'curated-cashvertising',
    title: 'Cashvertising',
    author: 'Drew Eric Whitman',
    description:
      'How to use more than 100 secrets of ad-agency psychology to make big money. Tap into primal human desires to craft compelling sales copy.',
    category: 'Business',
    isCurated: true,
    pointsOnCompletion: 35,
    pointsReward: 35,
    totalPages: 208,
    totalAmount: 208,
    trendingRank: 46,
    bestSellerRank: 47,
  },
  {
    id: 'curated-confessions-advertising-man',
    title: 'Confessions of an Advertising Man',
    author: 'David Ogilvy',
    description:
      'Timeless principles on direct response advertising, client relationships, and campaign craft from the undisputed father of modern advertising.',
    category: 'Business',
    isCurated: true,
    pointsOnCompletion: 35,
    pointsReward: 35,
    totalPages: 192,
    totalAmount: 192,
    trendingRank: 47,
    bestSellerRank: 46,
  },
  {
    id: 'curated-win-friends-influence',
    title: 'How to Win Friends and Influence People',
    author: 'Dale Carnegie',
    description:
      'The classic handbook for building genuine interpersonal rapport and persuasion. Win people to your way of thinking with empathy and sincere appreciation.',
    category: 'Influence',
    isCurated: true,
    pointsOnCompletion: 40,
    pointsReward: 40,
    totalPages: 288,
    totalAmount: 288,
    trendingRank: 7,
    bestSellerRank: 4,
  },
  {
    id: 'curated-48-laws-of-power',
    title: 'The 48 Laws of Power',
    author: 'Robert Greene',
    description:
      'Three thousand years of power dynamics distilled into forty-eight pragmatic rules. Learn to navigate organizational politics and protect yourself.',
    category: 'Influence',
    isCurated: true,
    pointsOnCompletion: 50,
    pointsReward: 50,
    totalPages: 452,
    totalAmount: 452,
    trendingRank: 3,
    bestSellerRank: 13,
  },
  {
    id: 'curated-influence-cialdini',
    title: 'Influence: The Psychology of Persuasion',
    author: 'Robert B. Cialdini',
    description:
      'The foundational scientific study on why people say yes. Master reciprocity, commitment, social proof, authority, liking, and scarcity.',
    category: 'Influence',
    isCurated: true,
    pointsOnCompletion: 45,
    pointsReward: 45,
    totalPages: 336,
    totalAmount: 336,
    trendingRank: 24,
    bestSellerRank: 23,
  },
  {
    id: 'curated-never-split-the-difference',
    title: 'Never Split the Difference',
    author: 'Chris Voss',
    description:
      'Negotiating as if your life depended on it from a former FBI hostage negotiator. Deploy tactical empathy, calibrated questions, and calibrated pauses.',
    category: 'Influence',
    isCurated: true,
    pointsOnCompletion: 40,
    pointsReward: 40,
    totalPages: 288,
    totalAmount: 288,
    trendingRank: 11,
    bestSellerRank: 16,
  },
  {
    id: 'curated-why-we-want-you-to-be-rich',
    title: 'Why We Want You to Be Rich',
    author: 'Donald Trump & Robert Kiyosaki',
    description:
      'Two billionaire perspectives on financial education, entrepreneurship, and overcoming middle-class stagnation through smart risk taking.',
    category: 'Business',
    isCurated: true,
    pointsOnCompletion: 40,
    pointsReward: 40,
    totalPages: 368,
    totalAmount: 368,
    trendingRank: 50,
    bestSellerRank: 50,
  },
  {
    id: 'curated-facts-are-facts',
    title: "Facts are Facts: The Untold Story of India's Partition",
    author: 'Abdul Wali Khan',
    description:
      'A critical historical analysis examining the socio-political machinations behind the Partition of India, British policy, and constitutional politics.',
    category: 'Influence',
    isCurated: true,
    pointsOnCompletion: 35,
    pointsReward: 35,
    totalPages: 182,
    totalAmount: 182,
    trendingRank: 54,
    bestSellerRank: 54,
  },
];

export function findCuratedBook(id: string): CuratedBook | undefined {
  return CURATED_BOOKS.find((b) => b.id === id);
}
